# frozen_string_literal: true

GUMROAD_VAT_REGISTRATION_NUMBER = GlobalConfig.get("VAT_REGISTRATION_NUMBER", "EU372030009")
GUMROAD_AUSTRALIAN_BUSINESS_NUMBER = GlobalConfig.get("AUSTRALIAN_BUSINESS_NUMBER", "3000 3814 4483")
GUMROAD_CANADA_GST_REGISTRATION_NUMBER = GlobalConfig.get("CANADA_GST_REGISTRATION_NUMBER", "701850612 RT9999")
GUMROAD_QST_REGISTRATION_NUMBER = GlobalConfig.get("QST_REGISTRATION_NUMBER", "NR00086053")
GUMROAD_NORWAY_VAT_REGISTRATION = GlobalConfig.get("NORWAY_VAT_REGISTRATION", "2082039")
GUMROAD_UK_VAT_REGISTRATION = GlobalConfig.get("UK_VAT_REGISTRATION", "400134960")
GUMROAD_INDIA_GSTIN = GlobalConfig.get("INDIA_GSTIN", "9925USA29021OSI")
GUMROAD_JAPAN_JCT = GlobalConfig.get("JAPAN_JCT", "1700150130962")
GUMROAD_NEW_ZEALAND_GST = GlobalConfig.get("NEW_ZEALAND_GST", "147-042-426")
GUMROAD_NIGERIA_TIN = GlobalConfig.get("NIGERIA_TIN", "2501510000683")
GUMROAD_SINGAPORE_GST = GlobalConfig.get("SINGAPORE_GST", "M90375350L")
GUMROAD_SOUTH_KOREA_VAT = GlobalConfig.get("SOUTH_KOREA_VAT", "407-80-37146")
GUMROAD_SWITZERLAND_VAT = GlobalConfig.get("SWITZERLAND_VAT", "CHE-353.638.941")
GUMROAD_THAILAND_VAT = GlobalConfig.get("THAILAND_VAT", "993000527119")
GUMROAD_CANADA_BC_PST = GlobalConfig.get("CANADA_BC_PST", "PST-1486-2963")
GUMROAD_CANADA_SK_PST = GlobalConfig.get("CANADA_SK_PST", "7980949")
GUMROAD_CANADA_MB_RST = GlobalConfig.get("CANADA_MB_RST", "701850612MT0001")

REPORTING_S3_BUCKET = if Rails.env.production?
  GlobalConfig.get("REPORTING_S3_BUCKET_PROD", "gumroad-reporting")
else
  GlobalConfig.get("REPORTING_S3_BUCKET_DEV", "gumroad-reporting-dev")
end

GUMROAD_MERCHANT_DESCRIPTOR_PHONE_NUMBER = GlobalConfig.get("MERCHANT_DESCRIPTOR_PHONE", "(650)742-3913") # Must be 10-14
GUMROAD_MERCHANT_DESCRIPTOR_URL = GlobalConfig.get("MERCHANT_DESCRIPTOR_URL", "gumroad.com/c") # Must be 0-13

GUMROAD_LOGO_URL = GlobalConfig.get("LOGO_URL", "https://gumroad.com/button/button_logo.png")

module GumroadAddress
  STREET = GlobalConfig.get("ADDRESS_STREET", "548 Market St")
  CITY = GlobalConfig.get("ADDRESS_CITY", "San Francisco")
  STATE = GlobalConfig.get("ADDRESS_STATE", "CA")
  ZIP = GlobalConfig.get("ADDRESS_ZIP", "94104")
  ZIP_PLUS_FOUR = "#{ZIP}-#{GlobalConfig.get("ADDRESS_ZIP_PLUS_FOUR", "5401")}"
  COUNTRY = ISO3166::Country[GlobalConfig.get("ADDRESS_COUNTRY", "US")]

  def self.full
    "#{STREET}, #{CITY}, #{STATE} #{ZIP_PLUS_FOUR}, #{COUNTRY.alpha3}"
  end
end
