test:
  service: S3
  endpoint: <%= GlobalConfig.get("AWS_S3_ENDPOINT") %>
  access_key_id: <%= GlobalConfig.get("AWS_ACCESS_KEY_ID") %>
  secret_access_key: <%= GlobalConfig.get("AWS_SECRET_ACCESS_KEY") %>
  region: us-east-1
  bucket: <%= PUBLIC_STORAGE_S3_BUCKET %>
  public: true
  force_path_style: true

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
amazon:
  service: S3
  access_key_id: <%= GlobalConfig.get("AWS_ACCESS_KEY_ID") %>
  secret_access_key: <%= GlobalConfig.get("AWS_SECRET_ACCESS_KEY") %>
  region: us-east-1
  bucket: <%= PUBLIC_STORAGE_S3_BUCKET %>
  public: true
